### ISSUE TITLE
Beautify – how should one set that up to work with atom-language-javascript-jxa ?

### ISSUE THREAD

**Issue by RobTrew** [danielbayley/atom-language-javascript-jxa#1]
Any experience of getting Beautify to work with atom-language-javascript-jxa ?

**Comment by danielbayley** [comment]
I don't think there's a linter or any such tool specifically for _JavaScript for Automation_, but since it's basically just JavaScript you should be able to beautify it with the same tools as vanilla JavaScript I would have thought. If that doesn't already work, maybe the _grammar scope_ (`source.js.jxa`) would need adding somewhere in the tool chain… like the [atom-beautify](https://atom.io/packages/atom-beautify) package itself probably.

**Comment by RobTrew** [comment]
Thanks, I've submitted a pull request to the JavaScript grammar of atom-beautify (to allow the .scpt extension and the JavaScript for Automation (JXA) grammar.

https://github.com/Glavin001/atom-beautify/pull/960

In the meanwhile, I'm just using a Keyboard Maestro macro which flips the grammar out of JXA to JS, applies Beautify (for JavaScript) and then returns to JXA.

**Comment by danielbayley** [comment]
@RobTrew Cool. I made a small suggestion on the comments, since that array should probably match the `fileTypes:` [one in this package](https://github.com/danielbayley/atom-language-javascript-jxa/blob/master/grammars/jxa.cson#L3-L7).

**Comment by RobTrew** [comment]
Thanks !

The .applescript extension is a curious issue – it's used by Script Editor as the default text file extension for JavaScript for Automation files.

Possibly an argument for its inclusion in your fileTypes ?

**Comment by danielbayley** [comment]
> The .applescript extension is a curious issue – it's used by Script Editor as the default text file extension for JavaScript for Automation files.

@RobTrew Apple's implementation of _JXA_ is really sloppy, so that pretty much sums it up!

I think there's a way to use CoffeeScript as an abstraction on top of it so I'll either be using that, shell scripts or Swift to automate most things in future.

> Possibly an argument for its inclusion in your fileTypes ?

I suppose it is; I'll include it in the next update. So maybe leave it in [your PR](https://github.com/Glavin001/atom-beautify/pull/960), but add the missing `fileTypes:`. 👍
